import jsPDF from 'jspdf'
import { getLoraApplicationUrl, getLoraTransactionUrl } from '../services/humanitarianExplorer'

export interface CampaignPdfApproval {
  address: string
  timestamp: string
  txId: string
}

export interface CampaignPdfDisbursement {
  name: string
  address: string
  amount: number
  txId: string
}

export interface CampaignPdfInput {
  name: string
  location: string
  type: string
  campaignId: number
  createdAt?: string
  totalUsdc: number
  approvals: CampaignPdfApproval[]
  disbursements: CampaignPdfDisbursement[]
}

export function generateCampaignPDF(campaign: CampaignPdfInput): void {
  const doc = new jsPDF()
  const contractId = import.meta.env.VITE_DISASTER_APP_ID || '—'
  const appUrl = contractId ? getLoraApplicationUrl(Number(contractId)) : ''

  doc.setFontSize(20)
  doc.setTextColor(40, 40, 40)
  doc.text('AlgoVault — Disaster Relief Campaign Report', 20, 25)

  doc.setFontSize(10)
  doc.setTextColor(120, 120, 120)
  doc.text(`Generated: ${new Date().toISOString()}`, 20, 35)
  doc.text('Network: Algorand Testnet', 20, 42)
  doc.text(`Contract: ${contractId}`, 20, 49)

  doc.setDrawColor(200, 200, 200)
  doc.line(20, 55, 190, 55)

  doc.setFontSize(14)
  doc.setTextColor(40, 40, 40)
  doc.text('Campaign Details', 20, 65)

  doc.setFontSize(10)
  doc.text(`Name: ${campaign.name}`, 20, 75)
  doc.text(`Event: ${campaign.location} · ${campaign.type}`, 20, 82)
  doc.text(`Campaign ID: ${campaign.campaignId}`, 20, 89)
  if (campaign.createdAt) doc.text(`Created: ${campaign.createdAt}`, 20, 96)
  doc.text(`Total Disbursed: ${campaign.totalUsdc} USDC`, 20, campaign.createdAt ? 103 : 96)

  let y = campaign.createdAt ? 118 : 111
  doc.setFontSize(14)
  doc.text('Multi-Signature Approval Record', 20, y)
  y += 10

  if (campaign.approvals.length === 0) {
    doc.setFontSize(9)
    doc.setTextColor(80, 80, 80)
    doc.text('No approval transactions recorded in this session.', 20, y)
    y += 12
  } else {
    campaign.approvals.forEach((a, i) => {
      doc.setFontSize(9)
      doc.setTextColor(40, 40, 40)
      doc.text(`Approver ${i + 1}: ${a.address}`, 20, y)
      doc.text(`Signed: ${a.timestamp}`, 20, y + 6)
      if (a.txId) {
        doc.text(`Txn: ${a.txId}`, 20, y + 12)
        doc.setTextColor(0, 100, 200)
        doc.text(getLoraTransactionUrl(a.txId), 20, y + 18)
      }
      y += 26
    })
  }

  doc.setTextColor(40, 40, 40)
  doc.setFontSize(9)
  doc.text('Status: Approved — 2 of 2 signatures received', 20, y + 4)

  doc.addPage()
  doc.setFontSize(14)
  doc.text('Disbursement Records', 20, 25)

  let tableY = 40
  doc.setFontSize(9)
  doc.setTextColor(80, 80, 80)
  doc.text('Beneficiary', 20, tableY)
  doc.text('USDC', 90, tableY)
  doc.text('Transaction ID', 115, tableY)
  doc.line(20, tableY + 3, 190, tableY + 3)

  campaign.disbursements.forEach((d) => {
    tableY += 16
    if (tableY > 270) {
      doc.addPage()
      tableY = 25
    }
    doc.setTextColor(40, 40, 40)
    const label = d.name || `${d.address.slice(0, 16)}…`
    doc.text(label.slice(0, 28), 20, tableY)
    doc.text(String(d.amount), 90, tableY)
    const txShort = d.txId ? `${d.txId.slice(0, 20)}…` : '—'
    doc.text(txShort, 115, tableY)
    if (d.txId) {
      doc.setTextColor(0, 100, 200)
      doc.setFontSize(8)
      doc.text(`lora.algokit.io/testnet/transaction/${d.txId}`, 20, tableY + 6)
      doc.setFontSize(9)
    }
  })

  doc.addPage()
  doc.setFontSize(10)
  doc.setTextColor(100, 100, 100)
  doc.text('This report was generated by AlgoVault on Algorand Testnet', 20, 25)
  doc.text('All transactions are immutably recorded on the Algorand blockchain.', 20, 35)
  if (appUrl) doc.text(`Verify at: ${appUrl}`, 20, 45)
  doc.text('All transactions verifiable at lora.algokit.io/testnet', 20, 55)

  doc.save(`algovault-campaign-${campaign.campaignId}-${Date.now()}.pdf`)
}
